-- Dynamically generated by Matugen for Hyprland 0.56+
local colors = {
    background = "rgba({{colors.background.default.hex_stripped}}ff)",
    foreground = "rgba({{colors.on_surface.default.hex_stripped}}ff)",
    active_border_1 = "rgba({{colors.primary.default.hex_stripped}}ee)",
    active_border_2 = "rgba({{colors.secondary.default.hex_stripped}}99)",
    inactive_border = "rgba({{colors.surface_container.default.hex_stripped}}88)",
    accent = "rgba({{colors.primary.default.hex_stripped}}ff)",
}

return colors
